version: '2'
services:
    jhipstersamplemongodb-app:
        image: jhipstersamplemongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://jhipstersamplemongodb-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=jhipsterSampleMongodb
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipstersamplemongodb-mongodb:
        extends:
            file: mongodb.yml
            service: jhipstersamplemongodb-mongodb
